name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run python examples script
      run: |
        pip install torch 
        ./run_python_examples.sh "install_deps,run_all,clean"
